### PR TITLE
Fix tooltip rendering bug.

### PR DESCRIPTION
**Pull request by AHilyard**
This change fixes the glitchy tooltip rendering that has been cropping up recently.

### CODE REVIEW

**Comment by SSKirillSS** [comment]
Thanks for your work!

**Comment by RobertHDPotatoes** [comment]
Although this does make the tooltips not glitch out like crazy, they still don't display properly. LegendaryTooltips will overlap on top of Relics that are Uncommon, Rare, or Epic rarity. I could remove the rarity's in the LegendaryTooltip file but then no items at all (besides relics) will have borders unless manually added

**Comment by AHilyard** [comment]
@RobertHDPotatoes That is a separate issue from what was fixed in this PR.  Please open a new issue on LegendaryTooltips and I will look into it for you.

**Comment by RobertHDPotatoes** [comment]
@AHilyard Okay, I've made a new issue. Thank you for taking your time to check out my issue.

**Pull request merged**
